I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 39, in script
    $ dedicacion = positiveAdd(dedicacion, 5)
  File "game/script.rpy", line 39, in <module>
    $ dedicacion = positiveAdd(dedicacion, 5)
NameError: name 'positiveAdd' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 39, in script
    $ dedicacion = positiveAdd(dedicacion, 5)
  File "C:\Users\maxim\Downloads\renpy-8.1.1-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\maxim\Downloads\renpy-8.1.1-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 39, in <module>
    $ dedicacion = positiveAdd(dedicacion, 5)
NameError: name 'positiveAdd' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
La Guerra de Excalibur 1.0
Fri Jun 16 15:05:31 2023
